export const CHECK_WINDOW_SIZE = 'CHECK_WINDOW_SIZE';

export const SET_SECTIONS = 'SET_SECTIONS';
export const SET_POSITIONS = 'SET_POSITIONS';
export const SET_SCREEN = 'SET_SCREEN';
export const SET_SECTION_ID = 'SET_SECTION_ID';
export const SECTION_ANIMATION_LEFT = 'SECTION_ANIMATION_LEFT';
export const SECTION_ANIMATION_RIGHT = 'SECTION_ANIMATION_RIGHT';

export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';

export const HIDE_UI = 'HIDE_HAMBURGER';
export const SET_HEADER = 'SET_HEADER';
export const UNSET_HEADER = 'UNSET_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';
export const SHOW_HEADER = 'SHOW_HEADER';
export const CHECK_STORY = 'CHECK_STORY';
export const INCREASE_STORY = 'INCREASE_STORY';
export const DECREASE_STORY = 'DECREASE_STORY';
export const INCREASE_COUNT_STORY = 'INCREASE_COUNT_STORY';
export const HIDE_TEXT = 'HIDE_TEXT';
export const SET_COUNT_SCROLL = 'SET_COUNT_SCROLL';
export const SET_COUNT_SCROLL_CHAPTERS = 'SET_COUNT_SCROLL_CHAPTERS';




